version: "3.9"

services:
  build:
    image: node:18-alpine
    working_dir: /app
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    command: >
      sh -c "npm ci && npm run build"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./.next:/app/.next

volumes:
  node_modules:
